name: todo-dev
# include services that are implemented
services:
  task-db:
    image: mysql:8.0
    container_name: task_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tasksdb
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppass"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks: [app-net]

  # migration（dbmate） after sucess run, exit
  dbmate:
    image: amacneil/dbmate:latest
    container_name: task_dbmate
    depends_on:
      task-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:pass@task-db:3306/tasksdb?parseTime=true&loc=UTC&charset=utf8mb4"
    volumes:
      - ./task/migrations:/db/migrations:ro
    command: ["up"]
    restart: "no"
    networks: [app-net]

  task-service:
    build:
      context: ./task
      dockerfile: ./Dockerfile
    depends_on:
      task-db:
        condition: service_healthy
      dbmate:
        condition: service_completed_successfully
    environment:
      PORT: "8081"
      DB_HOST: "task-db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: "pass"
      DB_NAME: "tasksdb"
      # if use DATABASE_URL，then add this：
      # DATABASE_URL: "mysql://root:pass@mysql:3306/tasksdb?parseTime=true&loc=UTC&charset=utf8mb4"
    ports:
      - "8081:8081"
    networks: [app-net]


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: task_phpmyadmin
    depends_on:
      task-db:
        condition: service_healthy
    environment:
      PMA_HOST: task-db      
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 64M      
    ports:
      - "8082:80"              
    networks: [app-net]

networks:
  app-net:
