FROM golang:1.24.2-alpine

WORKDIR /app

# Install git so Go modules can download dependencies
RUN apk add --no-cache git

# Copy and download dependencies
COPY go.mod ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the Go app
RUN go build -o team-service

# Run the binary
CMD ["./team-service"]
