# Conduktor Console configuration for Todo Project
# This connects to the existing Kafka cluster (dev_kafka) in the main project
# 
# Usage: 
# 1. Make sure main project Kafka is running: docker-compose up -d kafka
# 2. Start Conduktor: cd conduktor && docker-compose -f docker-compose-fixed.yml up -d
# 3. Access Conduktor at: http://localhost:8087
#
# NOTE: Changed port from 8080 to 8087 to avoid conflicts with task service (8081)

name: conduktor-monitoring

services:
  # Conduktor Console - monitoring UI for our project's Kafka
  conduktor-console:
    image: conduktor/conduktor-console:1.37.0
    container_name: conduktor_console
    ports:
      - "8087:8080"  # Changed from 8080 to 8087 to avoid conflicts with task service (8081)
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:change_me@postgresql:5432/conduktor-console"
      CDK_ORGANIZATION_NAME: "todo-project"
      # Main cluster configuration - pointing to our project's Kafka
      CDK_CLUSTERS_0_ID: "todo-dev-kafka"
      CDK_CLUSTERS_0_NAME: "Todo Dev Kafka"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "dev_kafka:9092"  # Our project's Kafka
      CDK_CLUSTERS_0_COLOR: "#FF6B35"
      CDK_CLUSTERS_0_ICON: "kafka"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - conduktor-net
      - todo-app-net  # Connect to project's network to access dev_kafka
    restart: unless-stopped

  # Conduktor's metadata database
  postgresql:
    image: postgres:14
    container_name: conduktor_postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduktor -d conduktor-console"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - conduktor-net
    restart: unless-stopped

volumes:
  pg_data: {}
  conduktor_data: {}

networks:
  conduktor-net:
    driver: bridge
  todo-app-net:
    external: true
    name: todo-dev_app-net  # Reference to main project's network
