name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    name: Build Docker Images for Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth, task, team, api-gateway, notification, realtime, frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service }} image
        run: |
          docker build -t ${{ matrix.service }} ./${{ matrix.service }}
